### ISSUE TITLE
After installing using pip: ImportError: No module named 'd6stack'

### ISSUE THREAD

**Issue by jpedrick** [d6t/d6tstack#1]
Python 3.5.5 :: Anaconda, Inc on Windows 7

d6stack shows up in "pip list"

However, I get an error when importing even from a python console.

I do see .pyc files in 'Lib/site-packages/d6stack/__pycache__/'

**Comment by d6tdev** [comment]
Did you miss the "t" `import d6stack` instead of `import d6tstack`?

**Comment by jpedrick** [comment]
That worked. Thanks.
