### ISSUE TITLE
Automatically appending \n in last column of df

### ISSUE THREAD

**Issue by girijesh18** [d6t/d6tstack#14]
Hi,
Whenever I am dumping data using d6tstack it is appending a \n (escape character at the end of each row of the last column). Any suggestions that how can I tackle such situations.
Any response would be highly appreciated.
Thanks

**Comment by d6tdev** [comment]
can you pls provide more details on what function you're running and some fake sample data?

**Comment by girijesh18** [comment]
Thanks for replying
d6tstack.utils.pd_to_mysql(df, 'mysql+mysqlconnector://dbName:dbPassword@dbLink/dbName', fileName)

I have trimmed data for whitespaces but still getting the same issue.

It would be great if you can address this issue as well [(https://github.com/d6t/d6tstack/issues/9)
].

Also is there any method to increase the speed of dumping data in the database.

Thanks

**Comment by d6tdev** [comment]
This was a windows issue it seems, though got \r instead of \n. Can you try the latest dev version? Example below seems to fix both the escape char and nans. Test on your actual data too.

`pip install git+https://github.com/d6t/d6tstack.git -U --no-deps`

```
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

uri = 'mysql+mysqlconnector://root:@localhost/test'
engine = create_engine(uri)
df = pd.DataFrame({'a':range(10),'b':'text'})
df.iloc[1,1]=np.nan; df.iloc[4,1]=np.nan;

# d6tstack
import d6tstack

d6tstack.utils.pd_to_mysql(df,uri,'test_pandas2',if_exists='replace')
dfc2 = pd.read_sql_table('test_pandas2', engine)
assert dfc2.equals(df)
assert dfc2['b'].isna().sum()==2
```

**Comment by d6tdev** [comment]
This was a windows issue it seems, though got \r instead of \n. Can you try the latest dev version 0.1.9? Example below seems to fix both the escape char and nans. Test on your actual data too.

`pip install git+https://github.com/d6t/d6tstack.git -U --no-deps`

```
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

uri = 'mysql+mysqlconnector://testusr:testpwd@localhost/testdb'
engine = create_engine(uri)
df = pd.DataFrame({'a':range(10),'b':'text'})
df.iloc[1,1]=np.nan; df.iloc[4,1]=np.nan;

# d6tstack
import d6tstack

d6tstack.utils.pd_to_mysql(df,uri,'test_pandas2',if_exists='replace')
dfc2 = pd.read_sql_table('test_pandas2', engine)
assert dfc2.equals(df)
assert dfc2['b'].isna().sum()==2
```

**Comment by d6tdev** [comment]
it should work, closing for now, reopen if it doesnt
