### ISSUE TITLE
Writing File in Chunk

### ISSUE THREAD

**Issue by girijesh97** [d6t/d6tstack#19]
Hi,
I am wondering that it is possible to write the file in chunk size because when I am trying to handle a large size file, my server is getting out of memory. Though your library is working outstanding for the small size of file. I am using the following method to write file in the database.

`d6tstack.utils.pd_to_mysql(meta_dataframe, 'mysql+mysqlconnector://abc:abc$12@paq.dshdhgytwya5e.us-east-1.rds.amazonaws.com/abcdb', meta_filename)`

How can I handle large size of files? Any suggestions would be great.

**Comment by girijesh97** [comment]
@sumanau7 Hi, I was not able to interpret your answer. I would like to explain my problem once again. I am uploading a CSV file and then converting to a data frame after that, by creating a connection I am trying to write that data frame as it is in the Database. This method is working fine when I have a small dataset but the size of the dataset is big ( like more than 10k) then my server is getting out of memory. This method creating a copy of the whole dataset. So I would like to know if it is possible to write this dataset in a chunk by chunk rather than in a single time

**Comment by d6tdev** [comment]
We've used `.pd_to_psql()` for very large files. `.pd_to_mysql()` works a bit different tested on reasonably sized files and it should work just as well. Can you add commands and error logs?
