### ISSUE TITLE
Issue with Schema Name

### ISSUE THREAD

**Issue by danielpoon** [d6t/d6tstack#3]
In the file:
/usr/local/lib/python3.7/site-packages/d6tstack/utils.py

> def pd_to_psql(df, uri, tablename, schema_name=None, if_exists='fail'):

This references schema_name, not schema so it throws an error when needing to use a schema. I fixed it via:

>     sql_engine = sqlalchemy.create_engine(uri, connect_args={'options': '-csearch_path={}'.format(schema_name)})

Please make the change in your code. Thanks.

Regards,
Cody Kirrabilli

**Comment by d6tdev** [comment]
Good catch, cleaned up several other issues. Updated in github, pypi publish shortly.
