### ISSUE TITLE
module 'd6tstack.utils' has no attribute 'pd_to_mssql'

### ISSUE THREAD

**Issue by jaiparkashyadav** [d6t/d6tstack#6]
Hi,

I was trying to use module 'd6tstack.utils'for mssql but gettign below error:

module 'd6tstack.utils' has no attribute 'pd_to_mssql'

Any chance of adding this sooner.

Regards,
Jai

**Comment by d6tdev** [comment]
are you using the latest version from github? pypi is slightly outdated

**Comment by jaiparkashyadav** [comment]
Thanks for quick reply...
I have used pip install command to install.is there any other way to
install, plz guide me...

Regards,
Jai

**Comment by d6tdev** [comment]
as per readme `pip install git+https://github.com/d6t/d6tstack.git`

pypi also updated.

note `pd_to_mssql()` hasn't been tested, let us know if it works

**Comment by d6tdev** [comment]
you been able to get this to work?

**Comment by jaiparkashyadav** [comment]
Thanks Dear for your help in installation...

But unfortunately it was just generating the CSVs properly and then giving
me the exceptions while bulk importing. So i had to use Pd.to_sql by maing
small chunks.

Regards,
Jai

**Comment by d6tdev** [comment]
Hmm ok. We've had trouble getting an mssql server set up for testing but seems we need to give that another go. Can you post the exception?

**Comment by jaiparkashyadav** [comment]
Hi ,

Unfortunately , i lost the error but as far as i can remember, it was
generating CSV properly and throwing exception while bulk import.

Regards,
Jai

**Comment by d6tdev** [comment]
closing for now when you find the error pls reopen
