### ISSUE TITLE
error while dumping NA values

### ISSUE THREAD

**Issue by girijesh18** [d6t/d6tstack#9]
Hi,
First of all, thank you very much for such a wonderful library.
I am facing while dumping data to MySQL database.
The NA and blank are getting either 'Null' or 'blank' randomly in the database.
For eg. If some value in CSV is 'null' or 'NA' then after dumping this kind of CSV into database these values become 'NA' or blank.

Can you please address this problem.

**Comment by d6tdev** [comment]
it should work, closing for now, reopen if it doesnt
